globals:
    $: true
    jQuery: true
rules:
    # Errors & best practices
    block-scoped-var: 1
    curly: [1, multi-line]
    default-case: 1
    eqeqeq: 2
    guard-for-in: 2
    linebreak-style: 0
    no-console: 0 # switch this to 2 to check if you have some console.logs trailing
    no-eval: 2
    no-multi-spaces: 2
    no-redeclare: 2
    no-unused-vars: 1
    no-use-before-define: 0
    no-eq-null: 2
    quotes: [2, single]
    semi: [2, always]
    # Style
    brace-style: [2, 1tbs, { allowSingleLine: true }]
    camelcase: 1
    comma-spacing: [2, { before: false, after: true }]
    comma-style: [2, last]
    computed-property-spacing: [2, never]
    consistent-this: [1, _this]
    indent: [1, "tab", { SwitchCase: 1 }]
    key-spacing: [2, {beforeColon: false, afterColon: true}]
    new-cap: 0
    no-bitwise: 2
    no-mixed-spaces-and-tabs: 2
    no-nested-ternary: 2
    no-trailing-spaces: 2
    one-var: [2, never]
    no-var: 2
    prefer-const: 1
    no-caller: 2
    no-new: 2
    no-undef: 2
    space-before-function-paren: ["error", "never"]
    object-curly-spacing: ["error", "never"]
    array-bracket-spacing: ["error", "never"]
    space-in-parens: ["error", "never"]
overrides:
    -   files: "*.vue"
        rules:
            indent: 0
env:
    es6: true
    browser: true
    node: true
extends: ["eslint:recommended", "plugin:vue/essential"]
parserOptions:
    sourceType: module
