<!--Do NOT change this file manually, it is being generated by 'fws icons' command.-->

<template>
    <component v-bind:is="component"/>
</template>

<script>
    import startcase from 'lodash.startcase';
    import ArrowDown from '../../../../assets/svg/ico-arrow-down.svg';
    import ArrowLeft from '../../../../assets/svg/ico-arrow-left.svg';
    import ArrowRight from '../../../../assets/svg/ico-arrow-right.svg';
    import ArrowUp from '../../../../assets/svg/ico-arrow-up.svg';
    import Bookmark from '../../../../assets/svg/ico-bookmark.svg';
    import Dog from '../../../../assets/svg/ico-dog.svg';
    import Happy from '../../../../assets/svg/ico-happy.svg';
    import Lock from '../../../../assets/svg/ico-lock.svg';
    import PlusCircle from '../../../../assets/svg/ico-plus-circle.svg';
    import User from '../../../../assets/svg/ico-user.svg';

    export default {
        props: {
            iconName: {
                type: String,
                required: true
            }
        },
        components: {
            ArrowDown,
            ArrowLeft,
            ArrowRight,
            ArrowUp,
            Bookmark,
            Dog,
            Happy,
            Lock,
            PlusCircle,
            User,

        },
        computed: {
            component() {
                return startcase(this.iconName.replace('ico-', '')).replace(' ', '');
            }
        }
    };
</script>
